version: '2.4.1'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    container_name: learnikia.nginx
    volumes:
      # - ./conf:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./html:/usr/share/nginx/html
      - ./html:/etc/nginx/www/pub
      - ./html2:/etc/nginx/www/pub2
    environment:
    - NGINX_HOST=local.host
    - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']